
name: Auto-pull
on:
  push:
    branches:
      - main # change to your branch name
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # add your private key as a secret
      - name: SSH into server and pull changes
        run: |
          ssh root@159.65.144.36 "cd /tmp/test && git pull"
