name: Auto Pull Workflow

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Push changes to server
        run: |
          scp -r ./ root@159.65.144.36:/tmp/test
      - name: Pull latest changes
        run: |
          ssh root@159.65.144.36 "cd /tmp/test && git pull"
