name: SSH Pull Workflow
on:
  push:
    branches:
      - main
jobs:
  ssh_pull_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        host: ${{ secrets.HOST }}
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Pull from remote repository
      run: |
        cd /tmp/test
        git pull

