name: Pull Code

on:
  push:
    branches:
      - main # replace with the name of your main branch

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          fetch-depth: 0
      - name: Pull code
        run: git pull
